application:
  mail:
    host: smtp.gmail.com
    port: 587
    protocol: SMTP
    user: office@ergobureau.com
    password: t46Gd*U8KJd6w1bS7
    tls: true
    auth: true
    quitwait: false

web:
  cdn:
    host: assets.ergobureau.com
    port:
    scheme:
